import type { CoreLayer, CoreLayerId } from "./coreTypes";

export const CORE_LAYERS: CoreLayer[] = [
  {
    id: "root-grove",
    name: "Root Culture Chamber",
    description: "Organic root cultures branch like living specimens.",
    unlockHint: "Always open.",
    order: 1,
    backgroundTheme: "grove",
    mood: "Baseline organism cultures and first growth.",
    coreDefinitionIds: ["root-core", "cell-cluster", "mycelium-strand"],
  },
  {
    id: "spiralarium",
    name: "Helix Incubator",
    description: "Rotating incubators for fast helix-shaped cultures.",
    unlockHint: "Reach 160 Essence.",
    order: 2,
    backgroundTheme: "spiral",
    mood: "Fast helix growth and quick extraction cycles.",
    coreDefinitionIds: ["spiral-core", "spiral-bloom"],
  },
  {
    id: "crystal-lattice",
    name: "Crystalline Containment",
    description: "Rigid containment for slow symmetric high-yield cultures.",
    unlockHint: "Reach 650 Essence.",
    order: 3,
    backgroundTheme: "crystal",
    mood: "Sharp symmetry and high-value extraction.",
    coreDefinitionIds: ["crystal-core"],
  },
  {
    id: "echo-field",
    name: "Memory Culture Bank",
    description: "Repeating motifs condense Genetic Patterns.",
    unlockHint: "Reach 950 Essence.",
    order: 4,
    backgroundTheme: "echo",
    mood: "Ghost cultures and Genetic Pattern income.",
    coreDefinitionIds: ["echo-core"],
  },
  {
    id: "verdant-plane",
    name: "Fern Growth Lab",
    description: "Fern strains print many small fronds at high Genome Complexity.",
    unlockHint: "Maintain 6 specimens and reach 2.40K Essence.",
    order: 5,
    backgroundTheme: "verdant",
    mood: "Dense leaf clusters and replication studies.",
    coreDefinitionIds: ["fern-core"],
  },
  {
    id: "storm-plane",
    name: "Electrogenic Chamber",
    description: "Electrogenic strains run fast micro-extraction cycles.",
    unlockHint: "Reach 4.20K Essence and 8 Genetic Patterns.",
    order: 6,
    backgroundTheme: "storm",
    mood: "Jagged bioelectric flashes and frequent extraction pulses.",
    coreDefinitionIds: ["lightning-core", "synapse-culture"],
  },
  {
    id: "inner-worlds",
    name: "Recursive Cell Vault",
    description: "Nested cultures multiply through late-game recursion.",
    unlockHint: "Stabilize 2 Mutations and open 5 chambers.",
    order: 7,
    backgroundTheme: "inner",
    mood: "Cells within cells, sealed for deep recursion.",
    coreDefinitionIds: ["recursive-core"],
  },
  {
    id: "entropy-rift",
    name: "Unstable Mutation Ward",
    description: "A future ward for unstable Chaos strains.",
    unlockHint: "Dormant.",
    order: 8,
    backgroundTheme: "entropy",
    mood: "Unstable cultures remain sealed.",
    coreDefinitionIds: ["mutation-mass"],
  },
  {
    id: "infinite-boundary",
    name: "Boundary Research Lab",
    description: "A future endgame lab for boundary organisms.",
    unlockHint: "Dormant.",
    order: 9,
    backgroundTheme: "boundary",
    mood: "Long-term boundary organism research.",
    coreDefinitionIds: ["boundary-seed"],
  },
];

export function getCoreLayer(id: CoreLayerId): CoreLayer | undefined {
  if (id === "all") return undefined;
  return CORE_LAYERS.find((layer) => layer.id === id);
}
