import type { CoreDefinition, CoreDefinitionId } from "./coreTypes";

export const CORE_DEFINITIONS: Record<CoreDefinitionId, CoreDefinition> = {
  "root-core": {
    id: "root-core",
    name: "Root Culture",
    description: "A baseline branching specimen. Cheap, steady, and dense.",
    layerId: "root-grove",
    fractalType: "root",
    baseCost: 14,
    costMultiplier: 1.18,
    baseBuildSpeed: 5.2,
    baseYieldPerNode: 1.15,
    outputTier: 0,
    baseComplexity: 9,
    visualTheme: { primary: 0x78ffb7, secondary: 0x9eb7ff },
    tags: ["branch", "recursive"],
  },
  "cell-cluster": {
    id: "cell-cluster",
    name: "Cell Cluster",
    description: "Mitosis-like cell colonies. Cheap culture density with steady extraction.",
    layerId: "root-grove",
    fractalType: "cell",
    baseCost: 85,
    costMultiplier: 1.2,
    baseBuildSpeed: 5.8,
    baseYieldPerNode: 1.05,
    outputTier: 1,
    baseComplexity: 11,
    unlockRequirement: { essence: 70 },
    visualTheme: { primary: 0x95ffd8, secondary: 0x4cd2ff },
    tags: ["branch", "stability"],
  },
  "mycelium-strand": {
    id: "mycelium-strand",
    name: "Mycelium Strand",
    description: "Fungal network cultures that reward many specimens and branch genes.",
    layerId: "root-grove",
    fractalType: "mycelium",
    baseCost: 420,
    costMultiplier: 1.24,
    baseBuildSpeed: 4.9,
    baseYieldPerNode: 1.45,
    outputTier: 2,
    baseComplexity: 14,
    unlockRequirement: { essence: 300, ownedCores: 3 },
    visualTheme: { primary: 0xb8ff8f, secondary: 0x7bf7c8 },
    tags: ["branch", "pattern"],
  },
  "spiral-core": {
    id: "spiral-core",
    name: "Helix Strain",
    description: "Fast circular growth. Lower yield, more frequent extractions.",
    layerId: "spiralarium",
    fractalType: "spiral",
    baseCost: 240,
    costMultiplier: 1.23,
    baseBuildSpeed: 7.1,
    baseYieldPerNode: 0.92,
    outputTier: 1,
    baseComplexity: 12,
    unlockRequirement: { essence: 160 },
    visualTheme: { primary: 0xd69aff, secondary: 0x78a6ff },
    tags: ["spiral", "mutation"],
  },
  "spiral-bloom": {
    id: "spiral-bloom",
    name: "Spiral Bloom",
    description: "A denser helix specimen with slower but richer curling growth.",
    layerId: "spiralarium",
    fractalType: "spiral",
    baseCost: 620,
    costMultiplier: 1.27,
    baseBuildSpeed: 5.9,
    baseYieldPerNode: 1.35,
    outputTier: 2,
    baseComplexity: 18,
    unlockRequirement: { essence: 500 },
    visualTheme: { primary: 0xd69aff, secondary: 0xffbf5b },
    tags: ["spiral", "recursive"],
  },
  "crystal-core": {
    id: "crystal-core",
    name: "Crystal Culture",
    description: "Slow symmetric lattices with high Essence yield.",
    layerId: "crystal-lattice",
    fractalType: "crystal",
    baseCost: 900,
    costMultiplier: 1.28,
    baseBuildSpeed: 3.5,
    baseYieldPerNode: 2.25,
    outputTier: 3,
    baseComplexity: 16,
    unlockRequirement: { essence: 650 },
    visualTheme: { primary: 0xcffcff, secondary: 0x75f4d7 },
    tags: ["symmetry", "stability"],
  },
  "echo-core": {
    id: "echo-core",
    name: "Memory Culture",
    description: "Repeats motifs and condenses Genetic Patterns.",
    layerId: "echo-field",
    fractalType: "echo",
    baseCost: 1500,
    costMultiplier: 1.3,
    baseBuildSpeed: 4.3,
    baseYieldPerNode: 1.25,
    outputTier: 3,
    baseComplexity: 14,
    unlockRequirement: { essence: 950 },
    visualTheme: { primary: 0xffd36e, secondary: 0x7bf7c8 },
    tags: ["pattern", "recursive"],
  },
  "fern-core": {
    id: "fern-core",
    name: "Fern Strain",
    description: "A branching variant that rewards dense specimen populations.",
    layerId: "verdant-plane",
    fractalType: "fern",
    baseCost: 3200,
    costMultiplier: 1.32,
    baseBuildSpeed: 4.7,
    baseYieldPerNode: 1.8,
    outputTier: 4,
    baseComplexity: 18,
    unlockRequirement: { essence: 2400, ownedCores: 6 },
    visualTheme: { primary: 0x8cff9e, secondary: 0x55d6a5 },
    tags: ["branch", "recursive"],
  },
  "lightning-core": {
    id: "lightning-core",
    name: "Electrogenic Strain",
    description: "Unstable bursts that print jagged bioelectric patterns.",
    layerId: "storm-plane",
    fractalType: "lightning",
    baseCost: 5200,
    costMultiplier: 1.36,
    baseBuildSpeed: 8.2,
    baseYieldPerNode: 1.35,
    outputTier: 4,
    baseComplexity: 15,
    unlockRequirement: { essence: 4200, patterns: 8 },
    visualTheme: { primary: 0xfff38a, secondary: 0x78a6ff },
    tags: ["mutation", "spiral"],
  },
  "synapse-culture": {
    id: "synapse-culture",
    name: "Synapse Culture",
    description: "Bioelectric neural clusters that trigger fast extraction pulses.",
    layerId: "storm-plane",
    fractalType: "lightning",
    baseCost: 9000,
    costMultiplier: 1.38,
    baseBuildSpeed: 9.4,
    baseYieldPerNode: 1.2,
    outputTier: 5,
    baseComplexity: 18,
    unlockRequirement: { essence: 7200, patterns: 18 },
    visualTheme: { primary: 0x4cd2ff, secondary: 0xfff38a },
    tags: ["mutation", "spiral"],
  },
  "recursive-core": {
    id: "recursive-core",
    name: "Recursive Culture",
    description: "Late-game nested organisms. Expensive, slow, and multiplicative.",
    layerId: "inner-worlds",
    fractalType: "recursive",
    baseCost: 18000,
    costMultiplier: 1.42,
    baseBuildSpeed: 2.9,
    baseYieldPerNode: 3.35,
    outputTier: 6,
    baseComplexity: 24,
    unlockRequirement: { essence: 14000, axioms: 2, unlockedLayers: 5 },
    visualTheme: { primary: 0xfff0c7, secondary: 0x7bf7c8 },
    tags: ["recursive", "pattern", "symmetry"],
  },
  "mutation-mass": {
    id: "mutation-mass",
    name: "Mutation Mass",
    description: "Unstable tissue with volatile high-yield mutation events.",
    layerId: "entropy-rift",
    fractalType: "mutation",
    baseCost: 36000,
    costMultiplier: 1.46,
    baseBuildSpeed: 3.7,
    baseYieldPerNode: 3.1,
    outputTier: 7,
    baseComplexity: 22,
    unlockRequirement: { essence: 24000, axioms: 3 },
    visualTheme: { primary: 0xff6eb4, secondary: 0xffbf5b },
    tags: ["mutation", "stability"],
  },
  "boundary-seed": {
    id: "boundary-seed",
    name: "Boundary Seed",
    description: "Endgame boundary organism. Dense orbital growth for deep research.",
    layerId: "infinite-boundary",
    fractalType: "boundary",
    baseCost: 120000,
    costMultiplier: 1.5,
    baseBuildSpeed: 2.2,
    baseYieldPerNode: 5.8,
    outputTier: 8,
    baseComplexity: 36,
    unlockRequirement: { essence: 90000, axioms: 6, unlockedLayers: 8 },
    visualTheme: { primary: 0xcffcff, secondary: 0xd69aff },
    tags: ["recursive", "symmetry"],
  },
};

export function getCoreDefinition(id: CoreDefinitionId): CoreDefinition {
  return CORE_DEFINITIONS[id];
}
