import type { Formula } from "./types";

// Future content can be added by extending this array; simulation reads effects from data.
export const formulas: Formula[] = [
  {
    id: "cell-division",
    name: "Cell Division",
    tag: "cell",
    description: "Nodes pulse with cellular rhythm. +55% node output, and pairs well with Branching effects.",
    unlockCost: 28,
    effect: { nodeProductionBonus: 0.55 },
    visualTags: ["recursive"],
    shortEffect: "+55% branch output",
  },
  {
    id: "branching-rule",
    name: "Branching Rule",
    tag: "branch",
    description: "Every full set of 10 nodes adds an 18% production multiplier.",
    unlockCost: 95,
    unlockRequires: { nodes: 7 },
    effect: { perTenNodesMultiplier: 0.18 },
    visualTags: ["branch"],
    shortEffect: "+18% per 10 Branches",
  },
  {
    id: "lattice-weave",
    name: "Lattice Weave",
    tag: "symmetry",
    description: "Every 5 nodes adds 4% production. If a Branch formula is active, weave another 22%.",
    unlockCost: 240,
    unlockRequires: { nodes: 11 },
    effect: { nodeMilestoneEvery: 5, nodeMilestoneMultiplier: 0.04, synergyTags: ["branch"], synergyMultiplier: 0.22 },
    visualTags: ["symmetry", "branch", "stability"],
    shortEffect: "+4% per 5 Branches",
  },
  {
    id: "pattern-echo",
    name: "Pattern Echo",
    tag: "pattern",
    description: "Repeated structures condense into Patterns and increase Essence by 18%.",
    unlockCost: 360,
    unlockRequires: { nodes: 15 },
    effect: { patternPerSecond: 0.09, essenceMultiplier: 1.18 },
    visualTags: ["pattern"],
    shortEffect: "Patterns + x1.18 Essence",
  },
  {
    id: "symmetry-boost",
    name: "Symmetry Boost",
    tag: "symmetry",
    description: "Balanced growth amplifies the whole fractal. Even node counts gain a stronger multiplier.",
    unlockCost: 700,
    unlockRequires: { nodes: 20 },
    effect: { symmetryMultiplier: 0.32 },
    visualTags: ["symmetry", "stability"],
    shortEffect: "Balanced growth x1.32",
  },
  {
    id: "spiral-growth",
    name: "Spiral Growth",
    tag: "spiral",
    description: "Production curls upward over time, gaining 2% per active minute in this fractal.",
    unlockCost: 1100,
    unlockRequires: { essenceEarned: 1300 },
    effect: { spiralPerMinuteMultiplier: 0.02 },
    visualTags: ["spiral"],
    shortEffect: "+2% per minute",
  },
  {
    id: "golden-recurrence",
    name: "Golden Recurrence",
    tag: "spiral",
    description: "Patterns feed back into Essence up to 35%. If a Pattern formula is active, add another 18%.",
    unlockCost: 1450,
    unlockRequires: { patternsEarned: 4 },
    effect: { patternEssenceMultiplier: 0.006, patternEssenceCap: 0.35, synergyTags: ["pattern"], synergyMultiplier: 0.18 },
    visualTags: ["spiral", "pattern"],
    shortEffect: "Patterns feed Essence",
  },
  {
    id: "nested-growth",
    name: "Nested Growth",
    tag: "nested",
    description: "Every unlocked formula increases node output by 5%. Stronger when your slots use different formula types.",
    unlockCost: 1900,
    unlockRequires: { essenceEarned: 2300 },
    effect: { nestedPerFormulaMultiplier: 0.05, diversityMultiplier: 0.08 },
    visualTags: ["recursive"],
    shortEffect: "+5% per discovered formula",
  },
  {
    id: "formula-mirror",
    name: "Formula Mirror",
    tag: "mirror",
    description: "The strongest equipped formula reflects into the weakest, adding a subtle global boost.",
    unlockCost: 3200,
    unlockRequires: { patternsEarned: 5 },
    effect: { mirrorStrength: 0.12 },
    visualTags: ["symmetry", "recursive"],
    shortEffect: "Strongest boosts weakest",
  },
  {
    id: "mini-fractal",
    name: "Mini Fractal",
    tag: "pattern",
    description: "A smaller bloom forms inside the root, unlocking Pattern generation and boosting Essence by 30%.",
    unlockCost: 820,
    unlockRequires: { nodes: 18 },
    effect: { patternUnlock: true, patternPerSecond: 0.07, essenceMultiplier: 1.28 },
    visualTags: ["pattern", "recursive"],
    shortEffect: "Unlock Patterns + x1.28",
  },
  {
    id: "origin-core",
    name: "Origin Core",
    tag: "core",
    description: "The first node remembers the initial spark, adding a permanent +2 Essence/sec while equipped.",
    unlockCost: 180,
    unlockRequires: { nodes: 10 },
    effect: { firstNodeFlatBonus: 2 },
    visualTags: ["recursive"],
    shortEffect: "+2 Essence/sec",
  },
  {
    id: "axiom-seed",
    name: "Axiom Seed",
    tag: "collapse",
    description: "Patterns sharpen Collapse rewards up to 25%. After Collapse, each Axiom adds +0.75 Essence/sec.",
    unlockCost: 2500,
    unlockRequires: { essenceEarned: 2800 },
    effect: { patternCollapseRewardMultiplier: 0.01, patternCollapseRewardCap: 0.25, axiomFlatBonus: 0.75 },
    visualTags: ["symmetry", "recursive"],
    shortEffect: "Patterns sharpen Collapse",
  },
  {
    id: "collapse-memory",
    name: "Collapse Memory",
    tag: "collapse",
    description: "The fractal folds more cleanly. Collapse rewards increase by 35%.",
    unlockCost: 1800,
    unlockRequires: { essenceEarned: 2200 },
    effect: { collapseRewardMultiplier: 0.35 },
    visualTags: ["mutation"],
    shortEffect: "+35% Collapse reward",
  },
  {
    id: "spiral-acceleration",
    name: "Spiral Acceleration",
    tag: "spiral",
    description: "Spiral Cores build faster and curl more tightly.",
    unlockCost: 520,
    unlockRequires: { essenceEarned: 700 },
    effect: { spiralPerMinuteMultiplier: 0.012, essenceMultiplier: 1.08 },
    visualTags: ["spiral"],
    shortEffect: "Spiral build speed + visual curl",
  },
  {
    id: "crystal-resonance",
    name: "Crystal Resonance",
    tag: "symmetry",
    description: "Crystal harvests resonate harder when symmetry is equipped.",
    unlockCost: 980,
    unlockRequires: { essenceEarned: 1200 },
    effect: { symmetryMultiplier: 0.18, synergyTags: ["symmetry"], synergyMultiplier: 0.12 },
    visualTags: ["symmetry", "stability"],
    shortEffect: "Crystal/symmetry harvest bonus",
  },
  {
    id: "echo-duplication",
    name: "Echo Duplication",
    tag: "pattern",
    description: "Echo motifs repeat and generate more Patterns.",
    unlockCost: 1450,
    unlockRequires: { patternsEarned: 3 },
    effect: { patternPerSecond: 0.12, essenceMultiplier: 1.08 },
    visualTags: ["pattern", "recursive"],
    shortEffect: "Echo motifs + Patterns",
  },
  {
    id: "grove-overgrowth",
    name: "Grove Overgrowth",
    tag: "branch",
    description: "Root Grove density increases production.",
    unlockCost: 1850,
    unlockRequires: { essenceEarned: 1800 },
    effect: { perTenNodesMultiplier: 0.08 },
    visualTags: ["branch", "recursive"],
    shortEffect: "Root density bonus",
  },
  {
    id: "harmonic-layering",
    name: "Harmonic Layering",
    tag: "nested",
    description: "Different unlocked layers harmonize into global production.",
    unlockCost: 2600,
    unlockRequires: { essenceEarned: 3000 },
    effect: { diversityMultiplier: 0.1 },
    visualTags: ["recursive", "stability"],
    shortEffect: "More layers, more output",
  },
  {
    id: "parallel-bloom",
    name: "Parallel Bloom",
    tag: "branch",
    description: "Every owned Core slightly accelerates all fractal printing.",
    unlockCost: 3400,
    unlockRequires: { essenceEarned: 4200 },
    effect: { essenceMultiplier: 1.12 },
    visualTags: ["branch", "recursive"],
    shortEffect: "Owned Cores boost speed",
  },
  {
    id: "pattern-archive",
    name: "Pattern Archive",
    tag: "pattern",
    description: "Stored Patterns increase Essence yield.",
    unlockCost: 4200,
    unlockRequires: { patternsEarned: 8 },
    effect: { patternEssenceMultiplier: 0.004, patternEssenceCap: 0.28 },
    visualTags: ["pattern", "stability"],
    shortEffect: "Patterns boost Essence",
  },
  {
    id: "recursive-seed",
    name: "Recursive Seed",
    tag: "nested",
    description: "Completed cycles spawn tiny bonus fractal echoes.",
    unlockCost: 5200,
    unlockRequires: { essenceEarned: 6500 },
    effect: { nestedPerFormulaMultiplier: 0.035 },
    visualTags: ["recursive"],
    shortEffect: "Micro-fractal echoes",
  },
  {
    id: "storm-conduction",
    name: "Storm Conduction",
    tag: "spiral",
    description: "Lightning cycles arc between branches and favor frequent harvests.",
    unlockCost: 6200,
    unlockRequires: { patternsEarned: 10 },
    effect: { essenceMultiplier: 1.16, spiralPerMinuteMultiplier: 0.01 },
    visualTags: ["mutation", "spiral"],
    shortEffect: "Lightning harvest tempo",
  },
  {
    id: "fern-replication",
    name: "Fern Replication",
    tag: "branch",
    description: "Patterns make Verdant fractals denser and more valuable.",
    unlockCost: 7600,
    unlockRequires: { essenceEarned: 8500 },
    effect: { patternEssenceMultiplier: 0.003, patternEssenceCap: 0.32, perTenNodesMultiplier: 0.05 },
    visualTags: ["branch", "recursive"],
    shortEffect: "Patterns feed Ferns",
  },
  {
    id: "axiom-memory",
    name: "Axiom Memory",
    tag: "collapse",
    description: "Collapsed runs leave a stronger old-seed echo.",
    unlockCost: 9200,
    unlockRequires: { axioms: 1 },
    effect: { collapseRewardMultiplier: 0.18, axiomFlatBonus: 0.45 },
    visualTags: ["recursive", "stability"],
    shortEffect: "Axioms strengthen runs",
  },
  {
    id: "core-choir",
    name: "Core Choir",
    tag: "core",
    description: "Different Core types resonate into a broader global multiplier.",
    unlockCost: 11800,
    unlockRequires: { essenceEarned: 12000 },
    effect: { diversityMultiplier: 0.12 },
    visualTags: ["recursive", "symmetry"],
    shortEffect: "Varied Cores scale",
  },
  {
    id: "deep-recursion",
    name: "Deep Recursion",
    tag: "nested",
    description: "Recursive Cores scale with discovered formulas and Axioms.",
    unlockCost: 16000,
    unlockRequires: { axioms: 2 },
    effect: { nestedPerFormulaMultiplier: 0.055, collapseRewardMultiplier: 0.12 },
    visualTags: ["recursive"],
    shortEffect: "Late recursive scaling",
  },
  {
    id: "infinite-boundary",
    name: "Infinite Boundary",
    tag: "nested",
    description: "A placeholder theorem for the future Boundary plane.",
    unlockCost: 26000,
    unlockRequires: { axioms: 4 },
    effect: { nestedPerFormulaMultiplier: 0.075, diversityMultiplier: 0.08 },
    visualTags: ["recursive", "stability"],
    shortEffect: "Endgame formula scaling",
  },
  {
    id: "singularity-bloom",
    name: "Singularity Bloom",
    tag: "collapse",
    description: "Collapse milestones bloom into stronger post-reset growth.",
    unlockCost: 42000,
    unlockRequires: { axioms: 6 },
    effect: { collapseRewardMultiplier: 0.42, axiomFlatBonus: 1.25 },
    visualTags: ["mutation", "recursive"],
    shortEffect: "Big Collapse scaling",
  },
  {
    id: "nutrient-medium",
    name: "Nutrient Medium",
    tag: "cell",
    description: "Cultures absorb richer medium for faster early growth.",
    unlockCost: 55,
    effect: { nodeProductionBonus: 0.22, essenceMultiplier: 1.08 },
    visualTags: ["stability"],
    shortEffect: "Early growth medium",
  },
  {
    id: "mycelial-spread",
    name: "Mycelial Spread",
    tag: "branch",
    description: "Root and mycelium strains spread into finer filament networks.",
    unlockCost: 1250,
    unlockRequires: { essenceEarned: 1500 },
    effect: { perTenNodesMultiplier: 0.1, synergyTags: ["branch"], synergyMultiplier: 0.15 },
    visualTags: ["branch", "pattern"],
    shortEffect: "Branch genes reinforce",
  },
  {
    id: "double-helix",
    name: "Double Helix",
    tag: "spiral",
    description: "Helix strains print paired growth curves.",
    unlockCost: 2100,
    unlockRequires: { essenceEarned: 2600 },
    effect: { spiralPerMinuteMultiplier: 0.018, essenceMultiplier: 1.1 },
    visualTags: ["spiral"],
    shortEffect: "Helix cultures accelerate",
  },
  {
    id: "prismatic-memory",
    name: "Prismatic Memory",
    tag: "symmetry",
    description: "Crystalline strains retain high-yield lattice echoes.",
    unlockCost: 5600,
    unlockRequires: { essenceEarned: 6200 },
    effect: { symmetryMultiplier: 0.24, nestedPerFormulaMultiplier: 0.025 },
    visualTags: ["symmetry", "stability"],
    shortEffect: "Crystal memory yield",
  },
  {
    id: "synaptic-surge",
    name: "Synaptic Surge",
    tag: "spiral",
    description: "Bioelectric strains discharge extra extraction pulses.",
    unlockCost: 8800,
    unlockRequires: { patternsEarned: 14 },
    effect: { essenceMultiplier: 1.18, spiralPerMinuteMultiplier: 0.012 },
    visualTags: ["mutation", "spiral"],
    shortEffect: "Synapse pulse bonus",
  },
  {
    id: "containment-mesh",
    name: "Containment Mesh",
    tag: "collapse",
    description: "Risky strains become easier to stabilize during extraction.",
    unlockCost: 13200,
    unlockRequires: { axioms: 2 },
    effect: { collapseRewardMultiplier: 0.16, patternCollapseRewardMultiplier: 0.004, patternCollapseRewardCap: 0.18 },
    visualTags: ["stability", "mutation"],
    shortEffect: "Stabilizes instability",
  },
  {
    id: "mutagenic-serum",
    name: "Mutagenic Serum",
    tag: "core",
    description: "Unstable cultures spike harder, but require containment protocols.",
    unlockCost: 18500,
    unlockRequires: { essenceEarned: 22000 },
    effect: { essenceMultiplier: 1.28, diversityMultiplier: 0.06 },
    visualTags: ["mutation"],
    shortEffect: "Risk strain multiplier",
  },
  {
    id: "nested-genome",
    name: "Nested Genome",
    tag: "nested",
    description: "Recursive organisms encode sub-cultures into each branch tip.",
    unlockCost: 23000,
    unlockRequires: { axioms: 3 },
    effect: { nestedPerFormulaMultiplier: 0.065, patternPerSecond: 0.1 },
    visualTags: ["recursive", "pattern"],
    shortEffect: "Sub-culture recursion",
  },
  {
    id: "structural-recall",
    name: "Structural Recall",
    tag: "collapse",
    description: "Stable Mutations preserve more lab structure between collapses.",
    unlockCost: 36000,
    unlockRequires: { axioms: 5 },
    effect: { collapseRewardMultiplier: 0.28, axiomFlatBonus: 0.9 },
    visualTags: ["stability", "recursive"],
    shortEffect: "Stable Mutation memory",
  },
  {
    id: "boundary-signal-gene",
    name: "Boundary Signal",
    tag: "nested",
    description: "A faint mathematical organism signal from beyond current containment.",
    unlockCost: 70000,
    unlockRequires: { axioms: 7 },
    effect: { nestedPerFormulaMultiplier: 0.09, diversityMultiplier: 0.12 },
    visualTags: ["recursive", "symmetry"],
    shortEffect: "Boundary scaling signal",
  },
];

export const formulaById = new Map(formulas.map((formula) => [formula.id, formula]));

export function getFormula(id: string): Formula | undefined {
  return formulaById.get(id);
}
