apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fractidle-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/esuarken/fractidle.git
  ref:
    branch: main
  # For a private repository, create a Flux secret and uncomment this:
  # secretRef:
  #   name: fractidle-repo-auth
